"""referentiels et vectorisation 384

Revision ID: 493abc5165d2
Revises: 0002_schema_initial
Create Date: 2026-08-09 11:58:10.335060+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

revision: str = '0003_referentiels'
down_revision: str | None = '0002_schema_initial'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frameworks',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('pillar', sa.Enum('privacy', 'cybersecurity', 'sustainability', name='pillar'), nullable=False),
    sa.Column('authority', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('celex_id', sa.String(length=20), nullable=True),
    sa.Column('license', sa.String(length=120), nullable=False),
    sa.Column('is_redistributable', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frameworks_code'), 'frameworks', ['code'], unique=True)
    op.create_table('framework_versions',
    sa.Column('framework_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('framework_id', 'label', name='uq_framework_version')
    )
    op.create_table('requirements',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('reference', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('kind', sa.Enum('chapter', 'section', 'article', 'paragraph', 'measure', name='requirement_kind'), nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=600), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['framework_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'reference', name='uq_requirement_reference')
    )
    op.create_index('ix_requirements_version', 'requirements', ['version_id'], unique=False)
    op.create_table('control_points',
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('expected_evidence', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column(
        'default_severity',
        postgresql.ENUM(
            'critical', 'major', 'minor', 'info',
            name='severity', create_type=False,  # type deja cree en 0002
        ),
        nullable=False,
    ),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_points_code'), 'control_points', ['code'], unique=False)
    op.create_table('crosswalks',
    sa.Column('source_requirement_id', sa.UUID(), nullable=False),
    sa.Column('target_requirement_id', sa.UUID(), nullable=False),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_requirement_id', 'target_requirement_id', name='uq_crosswalk')
    )
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=True)
    op.drop_index('ix_chunks_embedding_hnsw', table_name='document_chunks', postgresql_using='hnsw')
    # ### end Alembic commands ###


    op.execute(
        "CREATE INDEX ix_chunks_embedding_hnsw ON document_chunks "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.execute(
        "CREATE INDEX ix_requirements_embedding_hnsw ON requirements "
        "USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_requirements_embedding_hnsw")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_chunks_embedding_hnsw', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw')
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               existing_nullable=True)
    op.drop_table('crosswalks')
    op.drop_index(op.f('ix_control_points_code'), table_name='control_points')
    op.drop_table('control_points')
    op.drop_index('ix_requirements_version', table_name='requirements')
    op.drop_table('requirements')
    op.drop_table('framework_versions')
    op.drop_index(op.f('ix_frameworks_code'), table_name='frameworks')
    op.drop_table('frameworks')
    # ### end Alembic commands ###
